"""add uuid

Revision ID: a3e7edb9e06d
Revises: cc09c951e01d
Create Date: 2024-09-23 13:32:30.588767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e7edb9e06d'
down_revision: Union[str, None] = 'cc09c951e01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'projects', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users_token', ['id'])
    op.add_column('workspaces', sa.Column('uuid_workspace', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'workspaces', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='unique')
    op.drop_column('workspaces', 'uuid_workspace')
    op.drop_constraint(None, 'users_token', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    # ### end Alembic commands ###
