"""inits

Revision ID: af8ba300a811
Revises: 0500fd69512d
Create Date: 2024-09-22 16:05:40.264132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8ba300a811'
down_revision: Union[str, None] = '0500fd69512d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'projects', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users_token', ['id'])
    op.create_unique_constraint(None, 'workspaces', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='unique')
    op.drop_constraint(None, 'users_token', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    # ### end Alembic commands ###
